image:
  tag: 21.0.1-fpm-alpine

persistence:
  enabled: true
  storageClass: "local-path"
  annotations:
    "helm.sh/resource-policy": keep

externalDatabase:
  enabled: true
  type: mysql

internalDatabase:
  enabled: false

nextcloud:
  host: "cloud.unixfox.eu"
  extraEnv:
    - name: NEXTCLOUD_DATA_DIR
      value: "/data/nextcloud"
    - name: APACHE_DISABLE_REWRITE_IP
      value: "1"
  extraVolumeMounts:
    - name: slab
      mountPath: /data/nextcloud
  extraVolumes:
    - name: slab
      hostPath:
        path: /data/nextcloud

resources:
  limits:
    memory: 250Mi

tolerations:
  - key: app-nextcloud
    operator: Equal
    value: "true"
    effect: NoExecute

nodeSelector:
  kubernetes.io/hostname: nextfox

livenessProbe:
  initialDelaySeconds: 1800
  timeoutSeconds: 30
readinessProbe:
  timeoutSeconds: 30

nginx:
  enabled: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: buypass-prod
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;

      rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
  - secretName: chart-nextcloud-tls
    hosts:
    - cloud.unixfox.eu

redis:
  enabled: true
  cluster:
    enabled: false
  master:
    nodeSelector:
      kubernetes.io/hostname: nextfox
    tolerations:
      - key: app-nextcloud
        operator: Equal
        value: "true"
        effect: NoExecute
    persistence:
      enabled: false

keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: image.repository
      tag: image.tag