apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
data:
apiVersion: v1
data:
  config.json: |-
    {
      "nodePathMap": {{ .Values.nodePathMap | toPrettyJson | nindent 8 }}
    }
  setup: |-
    {{ .Values.configmap.setup | nindent 4 }}
  teardown: |-
    {{ .Values.configmap.teardown | nindent 4 }}
