Repository:
  backend:
    s3:
      endpoint: "s3.nl-ams.scw.cloud"
      bucket: "stash-invidious"
      region: "nl-ams"

BackupConfiguration:
  schedule: "0 */12 * * *"
  pvcname: "data-invidious-postgresql-0"
  retentionPolicy:
    name: default
    keepLast: 2
    prune: true