apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "invidious.fullname" . }}-ytproxy"
  labels:
    app: {{ template "invidious.name" . }}-ytproxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "invidious.name" . }}-ytproxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "invidious.name" . }}-ytproxy
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.ytproxy.securityContext.runAsUser }}
        runAsGroup: {{ .Values.ytproxy.securityContext.runAsGroup }}
        fsGroup: {{ .Values.ytproxy.securityContext.fsGroup }}
      hostNetwork: {{ .Values.ytproxy.hostNetwork }}
      {{- if .Values.ytproxy.affinity }}
      affinity: {{ toYaml .Values.ytproxy.affinity | nindent 8 }}
      {{- end }}
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /app/socket"]
        securityContext:
          allowPrivilegeEscalation: {{ .Values.ytproxy.securityContext.allowPrivilegeEscalation }}
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: sharedsock
          mountPath: /app/socket
      containers:
      - name: ytproxy
        image: "{{ .Values.ytproxy.image.repository }}:{{ .Values.ytproxy.image.tag }}"
        imagePullPolicy: {{ .Values.ytproxy.image.pullPolicy }}
        env:
        - name: DISABLE_WEBP
          value: "{{ .Values.ytproxy.disableWebp }}"
        - name: DISABLE_IPV6
          value: "{{ .Values.ytproxy.disableIpv6 }}"
        securityContext:
          allowPrivilegeEscalation: {{ .Values.ytproxy.securityContext.allowPrivilegeEscalation }}
        volumeMounts:
        - name: sharedsock
          mountPath: /app/socket
      restartPolicy: Always
      volumes:
      - name: sharedsock
        hostPath:
          path: /tmp/http-socket