{{- if .Values.ingress.enabled -}}
{{- $fullName := include "invidious.fullname" . -}}
{{- $name := include "invidious.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.main.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ $fullName }}"
              servicePort: http
  {{- end }}
---
{{- range $main := .Values.ingress.others }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ $main.path | replace "/" "" | replace "_" "-" }}"
  labels:
    app: {{ $name }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
{{- with $main.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range $hosts := $.Values.ingress.hosts }}
    - host: {{ $hosts }}
      http:
        paths:
          - path: {{ $main.path }}
            backend:
              serviceName: "{{ $fullName }}{{ $main.backend.serviceName }}"
              servicePort: http
  {{- end }}
---
{{- end }}
{{- end }}