apiVersion: v1
kind: Service
metadata:
  name: "{{ template "invidious.fullname" . }}-ytproxy"
  labels:
    app: {{ template "invidious.name" . }}-ytproxy
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: "{{ template "invidious.name" . }}-ytproxy"
    release: {{ .Release.Name }}
