# Default helm values for n8n.
# Default values within the n8n application can be found under https://github.com/n8n-io/n8n/blob/master/packages/cli/config/index.ts
defaults:

config:
  database:
    type: postgresdb
    postgresdb:
      host: n8n-stolon-proxy
      user: stolon
  generic:
    timezone: Europe/Brussels

## ALL possible n8n Values

#
#database:
#  type:             # Type of database to use - Other possible types ['sqlite', 'mariadb', 'mysqldb', 'postgresdb'] - default: sqlite
#  tablePrefix:      # Prefix for table names - default: ''
#  postgresdb:
#    database:       # PostgresDB Database - default: n8n
#    host:           # PostgresDB Host - default: localhost
#    password:        # PostgresDB Password - default: ''
#    port:            # PostgresDB Port - default: 5432
#    user:            # PostgresDB User - default: root
#    schema:            # PostgresDB Schema - default: public
#    ssl:
#      ca:            # SSL certificate authority - default: ''
#      cert:            # SSL certificate - default: ''
#      key:            # SSL key - default: ''
#      rejectUnauthorized:    # If unauthorized SSL connections should be rejected - default: true
#  mysqldb:
#    database:        # MySQL Database - default: n8n
#    host:            # MySQL Host - default: localhost
#    password:        # MySQL Password - default: ''
#    port:            # MySQL Port - default: 3306
#    user:            # MySQL User - default: root
#credentials:
#  overwrite:
#    data:        # Overwrites for credentials - default: "{}"
#    endpoint:    # Fetch credentials from API - default: ''
#
#executions:
#  process:                # In what process workflows should be executed - possible values [main, own] - default: own
#  timeout:                # Max run time (seconds) before stopping the workflow execution - default: -1
#  maxTimeout:            # Max execution time (seconds) that can be set for a workflow individually - default: 3600
#  saveDataOnError:        # What workflow execution data to save on error - possible values [all , none] - default: all
#  saveDataOnSuccess:    # What workflow execution data to save on success - possible values [all , none] - default: all
#  saveDataManualExecutions:    # Save data of executions when started manually via editor - default: false
#  pruneData:            # Delete data of past executions on a rolling basis - default: false
#  pruneDataMaxAge:        # How old (hours) the execution data has to be to get deleted - default: 336
#  pruneDataTimeout:        # Timeout (seconds) after execution data has been pruned - default: 3600
#generic:
#  timezone:     # The timezone to use - default: America/New_York
#path:         # Path n8n is deployed to - default: "/"
#host:         # Host name n8n can be reached - default: localhost
#port:         # HTTP port n8n can be reached - default: 5678
#listen_address: # IP address n8n should listen on - default: 0.0.0.0
#protocol:       # HTTP Protocol via which n8n can be reached - possible values [http , https] - default: http
#ssl_key:        # SSL Key for HTTPS Protocol - default: ''
#ssl_cert:       # SSL Cert for HTTPS Protocol - default: ''
#security:
#  excludeEndpoints: # Additional endpoints to exclude auth checks. Multiple endpoints can be separated by colon - default: ''
#  basicAuth:
#    active:     # If basic auth should be activated for editor and REST-API - default: false
#    user:       # The name of the basic auth user - default: ''
#    password:   # The password of the basic auth user - default: ''
#    hash:       # If password for basic auth is hashed - default: false
#  jwtAuth:
#    active:               # If JWT auth should be activated for editor and REST-API - default: false
#    jwtHeader:            # The request header containing a signed JWT - default: ''
#    jwtHeaderValuePrefix: # The request header value prefix to strip (optional) default: ''
#    jwksUri:              # The URI to fetch JWK Set for JWT authentication - default: ''
#    jwtIssuer:            # JWT issuer to expect (optional) - default: ''
#    jwtNamespace:         # JWT namespace to expect (optional) -  default: ''
#    jwtAllowedTenantKey:  # JWT tenant key name to inspect within JWT namespace (optional) - default: ''
#    jwtAllowedTenant:     # JWT tenant to allow (optional) - default: ''
#endpoints:
#  rest:       # Path for rest endpoint  default: rest
#  webhook:    # Path for webhook endpoint  default: webhook
#  webhookTest: # Path for test-webhook endpoint  default: webhook-test
#externalHookFiles: # Files containing external hooks. Multiple files can be separated by colon - default: ''
#nodes:
#  exclude: # Nodes not to load - default: "[]"
#  errorTriggerType: # Node Type to use as Error Trigger - default: n8n-nodes-base.errorTrigger

# Set additional environment variables on the Deployment
extraEnv:
  WEBHOOK_TUNNEL_URL: "https://n8n.unixfox.eu/"

image:
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: buypass-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.unixfox.eu/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.unixfox.eu/oauth2/start?rd=https://n8n.unixfox.eurequest_uri$is_args$args"
  hosts:
    - host: n8n.unixfox.eu
      paths:
        - "/"

  tls:
    - secretName: n8n-chart-tls
      hosts:
        - n8n.unixfox.eu

nodeSelector:
  topology.kubernetes.io/zone: eu-amsterdam-1-AD-1