apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-docker-registry"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ template "dockerregistry" . }}
type: kubernetes.io/dockerconfigjson