jobs:
  - name: purge-videos-table
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "0 12 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - '-c'
    - 'psql -U kemal -h stolon-proxy -c "TRUNCATE TABLE videos" invidious'
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"
  - name: vaccum-users-table
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "0 12 */3 * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - '-c'
    - 'psql -U kemal -h stolon-proxy -c "VACUUM FULL users" invidious'
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"
  - name: vaccum-soft-users-table
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - '-c'
    - 'psql -U kemal -h stolon-proxy -c "VACUUM FREEZE VERBOSE users" invidious'
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"