jobs:
  - name: purge-videos-table
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - -c
    - psql -U kemal -h stolon-proxy -c "DELETE FROM videos * WHERE updated < (now() - interval '6 hours')" invidious
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"
  - name: vaccum-users-table
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "0 12 * * MON"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - '-c'
    - 'psql -U kemal -h stolon-proxy -c "VACUUM FULL VERBOSE users" invidious'
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"
  - name: vaccum-soft-users-table
    suspend: true
    image:
      repository: postgres
      tag: 10
      imagePullPolicy: IfNotPresent
    schedule: "*/10 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: stolon
          key: pg_su_password
    command: ["/bin/sh"]
    args:
    - '-c'
    - 'psql -U kemal -h stolon-proxy -c "set vacuum_cost_delay to 50" invidious && psql -U kemal -h stolon-proxy -c "VACUUM FREEZE VERBOSE users" invidious'
    tolerations: []
    nodeSelector:
      topology.kubernetes.io/zone: "eu-amsterdam-1-AD-1"