{{- range $_, $cs := .Values.clusterSecrets }}
---
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: {{ required "A valid value for clustersecrets[*].name is required." $cs.name }}
  namespace: {{ $.Release.Namespace }}
  labels:{{ with $cs.labels }}{{ toYaml . | nindent 4 }}{{- end }}
{{ template "clustersecret.defaultLabels" $ }}
{{- with $cs.annotations }}
  annotations:{{ toYaml . | nindent 4 }}{{- end }}
{{- with $cs.matchNamespace }}
matchNamespace:
{{ toYaml . }}
{{- end }}
{{- with $cs.avoidNamespaces }}
avoidNamespaces:
{{ toYaml . }}
{{- end }}
{{ if $cs.type }}type: {{ $cs.type }}{{- end }}
data: {{ required "A valid value for clustersecrets[*].data is required." $cs.data | toYaml | nindent 2 }}
{{- end }}
