{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "clustersecret.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ template "clustersecret.defaultLabels" . }}
{{- with .Values.serviceAccount.annotations }}
  annotations:{{ toYaml . | nindent 4 }}{{- end }}
{{- with .Values.serviceAccount.imagePullSecretNames }}
imagePullSecrets:
{{- range $_, $name := . }}
- name: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
