apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: "{{ .Release.Name }}-pvc-backupconfig"
spec:
  task:
    name: pvc-backup
  repository:
    name: "{{ .Release.Name }}-s3-repo"
  schedule: "{{ .Values.BackupConfiguration.schedule | required "check values" }}"
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "{{ .Values.BackupConfiguration.pvcname | required "check values" }}"
  {{- with .Values.BackupConfiguration.retentionPolicy }}
  retentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}