apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: "{{ .Release.Name }}-s3-repo"
spec:
  backend:
    s3:
      endpoint: {{ .Values.Repository.backend.s3.endpoint | required "check values" }}
      bucket: {{ .Values.Repository.backend.s3.bucket | required "check values" }}
      region: {{ .Values.Repository.backend.s3.region | required "check values" }}
      prefix: "/stash-backup/pvc/{{ .Values.BackupConfiguration.pvcname | required "check values" }}"
    storageSecretName: "{{ .Release.Name }}-s3-secret"