apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-s3-secret"
type: Opaque
data:
  RESTIC_PASSWORD: {{ .Values.secrets.resticpassword | required "check values" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWSAccessKeyID | required "check values" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWSSecretAccessKey | required "check values" | b64enc }}