apiVersion: v1
kind: Service
metadata:
  name: {{ template "searx.fullname" . }}-morty
  labels:
    app: {{ template "searx.name" . }}-morty
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: {{ template "searx.name" . }}-morty
    release: {{ .Release.Name }}
