name: searx

searx:
  image:
    repository: unixfox/searx-custom
    tag: latest
    pullPolicy: Always
  replicaCount: 4
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 50
  nodeSelector: {}
  affinity: {}
  resources: {}
    #requests:
    #  cpu: 100m
    #  memory: 64Mi
    #limits:
    #  cpu: 800m
    #  memory: 512Mi

filtron:
  enabled: false
  image:
    repository: dalf/filtron
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 16
    targetCPUUtilizationPercentage: 50
  resources: {}
  nodeSelector: {}
  affinity: {}
    #requests:
    #  cpu: 100m
    #  memory: 64Mi
    #limits:
    #  cpu: 800m
    #  memory: 512Mi

morty:
  #key: ""
  image:
    repository: dalf/morty
    tag: latest
    pullPolicy: Always
  replicaCount: 0
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
  resources: {}
  nodeSelector: {}
  affinity: {}
    #requests:
    #  cpu: 100m
    #  memory: 64Mi
    #limits:
    #  cpu: 800m
    #  memory: 512Mi

ingress:
  enabled: true
  annotations:
    main:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: buypass-prod
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    search: {}
  hosts:
  - searx.be
  - www.searx.be
  tls:
   - secretName: chart-searx-tls
     hosts:
     - searx.be
     - www.searx.be