helmfiles:
  #- "releases/kube-system/main.yaml"
  #- "releases/longhorn-system/main.yaml"
  #- "releases/ingress-nginx/main.yaml"
  #- "releases/cert-manager/main.yaml"
  #- "releases/dns/main.yaml"
  #- "releases/cloud/main.yaml"
  #- "releases/searx/main.yaml"
  - "releases/nitter/main.yaml"
  #- "releases/monitoring/main.yaml"