keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: searx.image.repository
      tag: searx.image.tag

searx:
  nodeSelector:
    topology.kubernetes.io/zone: eu-amsterdam-1-AD-1

filtron:
  nodeSelector:
    topology.kubernetes.io/zone: eu-amsterdam-1-AD-1

morty:
  nodeSelector:
    topology.kubernetes.io/zone: eu-amsterdam-1-AD-1