keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: searx.image.repository
      tag: searx.image.tag

searx:
  nodeSelector: {}

filtron:
  nodeSelector:
    topology.kubernetes.io/zone: eu-amsterdam-1-AD-1

morty:
  nodeSelector:
    topology.kubernetes.io/zone: eu-amsterdam-1-AD-1
    kubernetes.io/arch: amd64

searxSettings:
  use_default_settings: true

  general:
    debug: False # Debug mode, only for development
    instance_name: "Searx Belgium" # displayed name
    contact_url: mailto:contact[at]searx.be

  # brand:
  #   git_url: https://github.com/searxng/searxng
  #   git_branch: master
  #   issue_url: https://github.com/searxng/searxng/issues
  #   new_issue_url: https://github.com/searxng/searxng/issues/new
  #   docs_url: https://searxng.github.io/searxng
  #   public_instances: https://searx.space
  #   wiki_url: https://github.com/searxng/searxng/wiki
  #   twitter_url: https://twitter.com/Searx_engine

  search:
    autocomplete: "google" # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off by default
    default_lang: "all" # Default search language - leave blank to detect from browser information or use codes from 'languages.py'
    ban_time_on_fail: 0 # ban time in seconds after engine errors
    max_ban_time_on_fail: 0 # max ban time in seconds after engine errors
    suspend_times:
      # Engine suspension time after error (in seconds; set to 0 to disable)
      # For error "Access denied" and "HTTP error [402, 403]"
      SearxEngineAccessDenied: 0
      # For error "CAPTCHA"
      SearxEngineCaptcha: 86400
      # For error "Too many request" and "HTTP error 429"
      SearxEngineTooManyRequests: 0
      # Cloudflare CAPTCHA
      cf_SearxEngineCaptcha: 1296000
      cf_SearxEngineAccessDenied: 86400
      # ReCAPTCHA
      recaptcha_SearxEngineCaptcha: 0

  server:
    bind_address: "0.0.0.0" # address to listen on
    base_url: "https://searx.be" # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
    image_proxy: True # Proxying image results through searx
    default_http_headers:
      X-Content-Type-Options : nosniff
      X-XSS-Protection : 1; mode=block
      X-Download-Options : noopen
      X-Robots-Tag : noindex, nofollow
      Referrer-Policy : no-referrer
      Content-Security-Policy : "upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src 'self' https://yewtu.be https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com"
      Feature-Policy : "accelerometer 'none';ambient-light-sensor 'none'; autoplay 'none';camera 'none';encrypted-media 'none';focus-without-user-activation 'none'; geolocation 'none';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none'; speaker 'none';sync-xhr 'none';usb 'none';vr 'none'"
      strict-transport-security : max-age=15724800; includeSubDomains; preload

  ui:
    query_in_title: true
    default_theme: oscar
    infinite_scroll: true

  outgoing:
    enable_http2: false
  
  categories_as_tabs:
    general:
    images:
    videos:
    files:
    it:
    news:
    map:
    music:
    science:
    social media:

  enabled_plugins:
    - 'Hash plugin'
    - 'Search on category select' 
    - 'Self Informations'
    - 'Tracker URL remover'
    - 'Hostname replace'  # see hostname_replace configuration below

  hostname_replace:
    '(.*\.)?youtube\.com$': 'yewtu.be'
    '(.*\.)?youtu\.be$': 'yewtu.be'
    '(.*\.)?youtube-noocookie\.com$': 'yewtu.be'
    '(.*\.)?reddit\.com$': 'old.reddit.com'
    '(.*\.)?redd\.it$': 'old.reddit.com'
    'mobile\.twitter\.com$': 'nitter.unixfox.eu'
    '(www\.)?twitter\.com$': 'nitter.unixfox.eu'
    '(.*\.)?btdigggink2pdqzqrik3blmqemsbntpzwxottujilcdjfz56jumzfsyd.onion$': 'btdig.com'
    '(.*\.)?brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion': 'search.brave.com'
    '(.*\.)?archiveiya74codqgiixo33q62qlrqtkgmcitqx5u2oeqnmn5bpcbiyd.onion': 'archive.is'

  engines:
    - name: z-library
      disabled: true
    - name: solidtorrents
      disabled: true
    - name: piped
      disabled: true
    - name: google videos
      disabled: true
    - name: brave.videos
      disabled: true
    - name: brave.images
      disabled: true
    - name: wikibooks
      disabled: true
    - name: wikiquote
      disabled: true
    - name: wikisource
      disabled: true
    - name: wikiversity
      disabled: true
    - name: wikivoyage
      disabled: true
    - name: arxiv
      disabled: true
    - name: apple maps
      enable_http2: true
      disabled: true
    - name: google scholar
      disabled: true
    - name: pubmed
      disabled: true
    - name: bing
      enable_http2: true
      disabled: true
    - name: duckduckgo
      disabled: true
    - name: brave
      disabled: true
    - name: qwant
      disabled: true
    - name: dictzone
      disabled: true
    - name: bing images
      disabled: true
    - name: qwant images
      disabled: true
    - name: artic
      disabled: true
    - name: deviantart
      disabled: true
    - name: flickr
      disabled: true
    - name: library of congress
      disabled: true
    - name: openverse
      disabled: true
    - name: unsplash
      disabled: true
    - name: unsplash
      disabled: true
    - name: bing videos
      disabled: true
    - name: qwant videos
      disabled: true
    - name: dailymotion
      disabled: true
    - name: sepiasearch
      disabled: true
    - name: vimeo
      disabled: true
    - name: youtube
      disabled: true
    - name: btdigg
      search_url: http://btdigggink2pdqzqrik3blmqemsbntpzwxottujilcdjfz56jumzfsyd.onion/search?q={search_term}&p={pageno}
      enable_http: true
      retry_on_http_error: true
      timeout: 5.0
      retries: 2
      proxies:
        all://:
          - socks5h://127.0.0.1:9050
    - name: invidious
      disabled: false
      enable_http: true
      base_url:
        - http://invidious-invidious.invidious.svc.cluster.local:3000
    - name: wikidata
      disabled: true
    - name: solidtorrents
      enable_http2: true
      base_url:
      - https://solidtorrents.net
      - https://solidtorrents.to
      - https://bitsearch.to
    - name: mojeek
      enable_http2: true
      timeout: 5.0
      proxies:
        all://:
          - socks5://127.0.0.1:9050
    - name: brave
      timeout: 5.0
      base_url: https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
      proxies:
        all://:
          - socks5h://127.0.0.1:9050