configuration:
  slackUsername: "kured"
  annotationTtl: "30m"
tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
image:
  repository: "quay.io/paulfantom/kured"
  tag: "1.8.2"
configuration:
  rebootCommand: "/usr/bin/systemctl reboot"