bases:
  - "../../../commons/repos.yaml"
  - "../../../commons/general.yaml"

releases:
- name: loki-stack
  labels:
    parent: monitoring
  namespace: monitoring
  chart: grafana/loki-stack
  values:
  - "values.yaml"