image:
  repository: quay.io/unixfox/botkube
  pullPolicy: Always
  ## default tag is appVersion from Chart.yaml. If you want to use
  ## some other tag then it can be specified here
  tag: b5b3a25
config:
  ## Resources you want to watch
  resources:
    - name: pod                # Name of the resources e.g pod, deployment, ingress, etc. (Resource name must be in singular form)
      namespaces:
        include:
          - all
        ignore:                 # List of namespaces to be ignored (omitempty), used only with include: all
          -                     # example : include [all], ignore [x,y,z] 
      events:                   # List of lifecycle events you want to receive, e.g create, update, delete, error OR all
        - error
    - name: service
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - delete
        - error
    - name: deployment
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.availableReplicas
    - name: statefulset
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.readyReplicas
    - name: ingress
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: node
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: namespace
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: persistentvolume
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: persistentvolumeclaim
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: configmap
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: daemonset
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.numberReady
    - name: job
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.conditions[*].type
    - name: role
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: rolebinding
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: clusterrole
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - error
    - name: clusterrolebinding
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - delete
        - error

  # Check true if you want to receive recommendations
  # about the best practices for the created resource
  recommendations: true

  ssl:                                           # For using custom SSL certificates
    enabled: false                               # Set to true and specify cert path in the next line after uncommenting
    #cert:                                       # SSL Certificate file e.g certs/my-cert.crt

  # Setting to support multiple clusters
  settings:
    # Cluster name to differentiate incoming messages
    clustername: "defaultnew"
    # Kubectl executor configs
    kubectl:
      # Set true to enable kubectl commands execution
      enabled: false
      # List of allowed commands
      commands:
        # method which are allowed
        verbs: ["api-resources", "api-versions", "cluster-info", "describe", "diff", "explain", "get", "logs", "top", "auth"]
        # resource configuration which is allowed
        resources: ["deployments", "pods" , "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes" ]
      # set Namespace to execute botkube kubectl commands by default
      defaultNamespace: default
      # Set true to enable commands execution from configured channel only
      restrictAccess: false
    # Set true to enable config watcher
    configwatcher: true
    # Set false to disable upgrade notification
    upgradeNotifier: true
communications:
  # Settings for Discord
  discord:
    enabled: true
    botid: '737588087261233193'         # BotKube Application Client ID 
    channel: '737592247792566333'   # Discord Channel id for receiving BotKube alerts 
    notiftype: short                # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)
