apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: "mysql"
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: "nfs-111-tcp"
    port: 111
    protocol: TCP
    targetPort: 111
  - name: "nfs-2048-tcp"
    port: 2048
    protocol: TCP
    targetPort: 2048
  - name: "nfs-2049"
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: "nfs-2050"
    port: 2050
    protocol: TCP
    targetPort: 2050
  - name: "nfs-111-udp"
    port: 111
    protocol: UDP
    targetPort: 111
  - name: "nfs-2048-udp"
    port: 2048
    protocol: UDP
    targetPort: 2048
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}