apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: nitter.unixfox.eu
    kompose.service.expose.tls-secret: nitter-tls
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nitter
  name: nitter
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: nitter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.service.expose: nitter.unixfox.eu
        kompose.service.expose.tls-secret: nitter-tls
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nitter
    spec:
      volumes:
      - name: config-nitter
        configMap:
          name: nitter
      containers:
        - image: zedeus/nitter
          volumeMounts:
          - name: config-nitter
            mountPath: /src/nitter.conf
            subPath: nitter.conf
          name: nitter
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
