apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: buypass-prod
    nginx.ingress.kubernetes.io/proxy-next-upstream: "http_429"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($uri = "/robots.txt") { return 200 "User-agent: *\nDisallow: /"; }
      if ($http_Accept_Language = "") { set $block true; }
      if ($http_Accept = "") { set $block true; }
      if ($http_Accept_Encoding = "") { set $block true; }
      if ($uri = "/") { set $block false; }
      if ($uri ~ "/pic/video(.*)") { set $block false; }
      if ($block = true) { return 403; }
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; connect-src 'self' https://*.twimg.com; manifest-src 'self'";
      more_set_headers "Feature-Policy: accelerometer 'none';ambient-light-sensor 'none'; autoplay 'none';camera 'none';encrypted-media 'none';focus-without-user-activation 'none'; geolocation 'none';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none'; speaker 'none';sync-xhr 'none';usb 'none';vr 'none'";
      more_set_headers "Referrer-Policy: no-referrer";
      more_set_headers "X-Robots-Tag: noindex, noarchive, nofollow";
    kompose.cmd: kompose convert -c
    kompose.service.expose: nitter.unixfox.eu
    kompose.service.expose.tls-secret: nitter-tls
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nitter
  name: nitter
spec:
  rules:
    - host: nitter.unixfox.eu
      http:
        paths:
          - backend:
              serviceName: nitter
              servicePort: 8080
  tls:
    - hosts:
        - nitter.unixfox.eu
      secretName: nitter-tls
status:
  loadBalancer: {}
