#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/wireguard
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

configmap:
  config:
    # -- Enables or disables the configMap
    enabled: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 2049
        protocol: TCP

# lifecycle:
#   postStart:
#     exec:
#       command: ["/bin/sh", "-c", "apt update; apt install -y 6tunnel"]

probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: false
  readiness:
    # -- Enable the readiness probe
    enabled: false
  startup:
    # -- Enable the startup probe
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  privileged: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- Default persistence for configuration files.
  # @default -- See below
  config:
    # -- Enables or disables the persistence item
    enabled: true
    type: custom
    volumeSpec:
      configMap:
        name: flynfs-config
    
    mountPath: /config
    # -- Specify if the volume should be mounted read-only.
    readOnly: false
  modules:
    enabled: true
    type: custom
    volumeSpec:
      hostPath:
        # directory location on host
        path: /lib/modules
        # this field is optional
        type: Directory
    
    mountPath: /lib/modules
    # -- Specify if the volume should be mounted read-only.
    readOnly: true
  source:
    enabled: false
  backups:
    enabled: false