nodeSelector:
  kubernetes.io/hostname: "ams-362691"
service:
  listen:
    enabled: false
  discovery:
    enabled: false
persistence:
  nextcloud:
    enabled: false
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    retain: true
    size: 1Gi
  syncthing1:
    enabled: true
    mountPath: /var/syncthing
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    retain: true
    size: 1Gi
env:
  STGUIADDRESS: "127.0.0.1:8384"
hostNetwork: true
dnsPolicy: "ClusterFirstWithHostNet"
tolerations:
  - key: dedicated-server
    operator: Equal
    value: "true"
    effect: NoExecute
dnsPolicy: "Default"
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    enabled: false
  readiness:
    # -- Enable the readiness probe
    enabled: false
  startup:
    # -- Enable the startup probe
    enabled: false