image:
  tag: v7.2.1

ingress:
  enabled: true
  path: /
  # Only used if API capabilities (networking.k8s.io/v1) allow it
  pathType: ImplementationSpecific
  # Used to create an Ingress record.
  hosts:
    - oauth.unixfox.eu
  # Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  # Warning! The configuration is dependant on your current k8s API version capabilities (networking.k8s.io/v1)
  # extraPaths:
  # - path: /*
  #   pathType: ImplementationSpecific
  #   backend:
  #     service:
  #       name: ssl-redirect
  #       port:
  #         name: use-annotation
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: buypass-prod
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: chart-oauth-tls
      hosts:
        - oauth.unixfox.eu

nodeSelector:
  kubernetes.io/arch: arm64

tolerations:
  - key: lowvm
    operator: Equal
    value: "true"
    effect: NoExecute