keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: image.repository
      tag: image.tag
    - repository: ytproxy.image.repository
      tag: ytproxy.image.tag

image:
  repository: unixfox/invidious-custom
  tag: api-new-build-eeb407bfdff8c9617ecdcd340c4c7a06200cca82-f8bd9c7e039f036d40bea260246cc9f3693e116d
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  primary:
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      runAsUser: 1000
    initContainers:
      - name: chmod
        image: busybox
        command: ['chmod', '-R', '777', '/var/run/postgresql']
        volumeMounts:
        - name: socket
          mountPath: /var/run/postgresql
    extraVolumeMounts:
      - name: socket
        mountPath: /var/run/postgresql
    extraVolumes:
      - name: socket
        hostPath:
          path: /var/run/postgresql-invidious-proxy
    nodeSelector:
      kubernetes.io/hostname: frhb71656ds
    tolerations:
    - key: dedicated-server
      operator: Equal
      value: "true"
      effect: NoExecute
    persistence:
      size: "200Gi"
      storageClass: "local-path"

ingress:
  enabled: true
  hosts:
  - '*.proxy.yewtu.be'
  tls:
   - secretName: chart-invidious-proxy-tls
     hosts:
     - '*.proxy.yewtu.be'

replicaCount: 3

hostNetwork: true
containerPorts: false

extraVolumesMounts:
  - name: postgressocket
    mountPath: /var/run/postgresql
extraVolumes:
  - name: postgressocket
    hostPath:
      path: /var/run/postgresql-invidious-proxy

affinity: {}

nodeSelector:
  kubernetes.io/hostname: frhb71656ds

tolerations:
  - key: dedicated-server
    operator: Equal
    value: "true"
    effect: NoExecute

ytproxy:
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
  affinity: {}

refresh:
  enabled: false

config:
  use_quic: false
  domain: eu.proxy.yewtu.be
  channel_threads: 0
  feed_threads: 0
  modified_source_code_url: https://github.com/unixfox/invidious-custom
  output: STDOUT
  log_level: Error
  full_refresh: false
  https_only: true
  force_resolve: ipv6
  decrypt_polling: true
  popular_enabled: true
  captcha_enabled: false
  login_enabled: true
  registration_enabled: true
  statistics_enabled: true
  external_port: 443
  default_user_preferences:
    annotations: false
    annotations_subscribed: false
    autoplay: true
    captions:
    - ""
    - ""
    - ""
    comments:
    - youtube
    - ""
    continue: false
    continue_autoplay: true
    dark_mode: ""
    latest_only: false
    listen: false
    local: true
    locale: en-US
    max_results: 40
    notifications_only: false
    player_style: invidious
    quality: hd720
    quality_dash: best
    default_home: Popular
    feed_menu:
    - Popular
    - Trending
    - Subscriptions
    - Playlists
    related_videos: true
    sort: published
    thin_mode: false
    unseen_only: false
    video_loop: false
    extend_desc: false
    volume: 100
    save_player_pos: false
  dmca_content: []
  check_tables: true
  cache_annotations: false
  hsts: true
  disable_proxy: false
  port: 3000
  pool_size: 100