#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: quay.io/pussthecatorg/bibliogram
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

configmap:
  config:
    # -- Enables or disables the configMap
    enabled: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 10407

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

configmap:
  config:
    enabled: true
    data:
      config.js: |
        module.exports = {
        }

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- Default persistence for configuration files.
  # @default -- See below
  config:
    # -- Enables or disables the persistence item
    enabled: true
    type: custom
    volumeSpec:
      configMap:
        name: bibliogram-config
    
    mountPath: /app/config.js
    subPath: config.js
    # -- Specify if the volume should be mounted read-only.
    readOnly: false
  db:
    enabled: true
    type: pvc
    mountPath: /app/db/
    # -- Specify if the volume should be mounted read-only.
    readOnly: false
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
  source:
    enabled: false
  backups:
    enabled: false