config:
  tenancy: ocid1.tenancy.oc1..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  user: ocid1.user.oc1..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  fingerprint: 8c:bf:17:7b:5f:e0:7d:13:75:11:d6:39:0d:e2:84:74
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    <snip>
    -----END RSA PRIVATE KEY-----
  region: EU_AMSTERDAM_1
  publicIpv4Address: 9.9.9.9 # optional
  publicIpv6Address: "fe80::1" # optional
  subnet: ocid1.subnet.oc1..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
nodeSelector:
  kubernetes.io/os: linux
affinity: {}
tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 5
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 5
resources: {}
# limits:
#   cpu: 10m
#   memory: 20Mi
# requests:
#   cpu: 10m
#   memory: 20Mi
image:
  repository: unixfox/oci-ha-floating-ip
  tag: "latest"
  pullPolicy: IfNotPresent
  runAsUser: 10001
  allowPrivilegeEscalation: false