apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: "{{ .Release.Name }}-rclone-repo"
spec:
  backend:
    rest:
      url: {{ .Values.Repository.rclone.remote | required "check values" }}
    storageSecretName: "{{ .Release.Name }}-secret"