Kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: "{{ .Release.Name }}-rclone-secret"
matchNamespace:
  - *
avoidNamespaces:
  - default
  - kube-public
data:
  {{ range $key, $value := .Values.rclone | required "check values" -}}
    {{ $key }}: {{ $value | b64enc }}
  {{- end -}}