Kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: "{{ .Release.Name }}-restic-secret"
matchNamespace:
  - *
avoidNamespaces:
  - default
  - kube-public
data:
  RESTIC_PASSWORD: {{ .Values.secrets.resticpassword | required "check values" | b64enc }}