apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-rclone-secret"
type: Opaque
data:
  {{ range $key, $value := .Values.rclone | required "check values" -}}
    {{ $key }}: {{ $value | b64enc }}
  {{- end -}}