ingress:
  enabled: false
parent:
  enabled: false
child:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - netcup-node02
            - k3s-master1
  configs:
    netdata:
      data: |
        [db]
          mode = none
        [web]
          allow connections from = 152.53.16.45 10.0.1.13 10.0.1.84
k8sState:
  enabled: false
  persistence:
    storageclass: "local-path"
  configs:
    netdata:
      data: |
        [global]
          hostname = k8s-state-invidious
        [db]
          mode = none
        [plugins]
          timex = no
          checks = no
          idlejitter = no
          tc = no
          diskspace = no
          proc = no
          cgroups = no
          enable running new plugins = no
          slabinfo = no
          perf = no
          go.d = yes
          ioping = no
          ebpf = no
          charts.d = no
          apps = no
          python.d = no
          fping = no