keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: nitter.image.repository
      tag: nitter.image.tag

nitter:
  image:
    repository: unixfox/nitter
    tag: latest

redis:
  enabled: true
  usePassword: false
  cluster:
    enabled: false
  slave:
    persistence:
      enabled: false
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - azurefreeelgasse
              - oraclefree3
              - oraclefree4
    persistence:
      enabled: false