keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: deployment.image.repository
      tag: deployment.image.tag

nitter:
  deployment:
    replicas: 5
    image:
      repository: quay.io/unixfox/nitter-tokens
      tag: latest
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: buypass-prod
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: static.nitter.unixfox.eu
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name:
              # -- Overrides the service port reference for this path
              port:
      -  # -- Host address. Helm template can be passed.
        host: nitter.unixfox.eu
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name:
              # -- Overrides the service port reference for this path
              port:
      -  # -- Host address. Helm template can be passed.
        host: mobile.nitter.unixfox.eu
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name:
              # -- Overrides the service port reference for this path
              port:

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls:
      - secretName: nitter-tls
        hosts:
          - nitter.unixfox.eu
          - static.nitter.unixfox.eu
          - mobile.nitter.unixfox.eu
