{{ if .Values.toProxy }}
{{- range $name, $config := .Values.toProxy }}
{{ if $config.externalName }}
kind: Service
apiVersion: v1
metadata:
  name: "{{ $name | replace "." "-" }}-proxy"
spec:
  type: ExternalName
  externalName: "{{ $config.externalName }}"
  ports:
  - port: {{ $config.servicePort }}
{{ end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $name | replace "." "-" }}-proxy"
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $config.tls }}
  tls:
    - hosts:
        - "{{ $name }}"
      secretName: "{{ $name | replace "." "-" }}-tls"
  {{- end }}
  rules:
  - host: "{{ $name }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: "{{ $name | replace "." "-" }}-proxy"
            port:
              number: {{ default 80 $config.servicePort }}
{{- end }}
{{ end }}