---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  scope: Namespaced
  group: clustersecret.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          matchNamespace:
            type: array
            items:
              type: string
          avoidNamespaces:
            type: array
            items:
              type: string
          data:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
    - csec
  additionalPrinterColumns:
  - name: Type
    type: string
    priority: 0
    JSONPath: .type
    description: Secret Type
