image:
  registry: ghcr.io
  repository: zcube/bitnami-compat/mariadb-galera
  tag: 10.6-debian-10
  pullPolicy: Always
db:
  user: "powerdns"
  name: "powerdns"
persistence:
  storageClass: "local-path"

replicaCount: 1

service:
  headless:
    publishNotReadyAddresses: true