apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  brudi.yml: {{ toYaml .Values.brudi.config | b64enc }}
  rclone.conf: {{ .Values.rclone.config | b64enc }}
  restic-password: {{ .Values.restic.password | b64enc }}