replicaCount: 2
# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: app.kubernetes.io/name
#           operator: In
#           values:
#           - coredns
#       topologyKey: kubernetes.io/hostname

service:
  clusterIP: 10.43.0.10

resources:
  limits:
    cpu: 0.5
    memory: 128Mi
  requests:
    cpu: 0.3
    memory: 128Mi

servers:
- zones:
  - zone: .
  port: 53
  plugins:
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
      configBlock: |-
        lameduck 5s
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . tls://9.9.9.10 tls://149.112.112.10
      configBlock: |
        tls_servername dns.quad9.net
        health_check 5s
    - name: cache
      parameters: 300
      configBlock: |-
        serve_stale
    - name: loop
    - name: reload
    - name: loadbalance
    - name: hosts
      configBlock: |
        2600:9000:2394:b600:10:3b78:a40:21 api.twitter.com
        fallthrough
    - name: rewrite
      parameters: name yewtu.be ingress-nginx-controller.ingress-nginx.svc.cluster.local