replicaCount: 3
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - coredns
      topologyKey: kubernetes.io/hostname

service:
  clusterIP: 10.43.0.10

servers:
- zones:
  - zone: .
  port: 53
  plugins:
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
      configBlock: |-
        lameduck 5s
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . tls://9.9.9.9 tls://149.112.112.112
      configBlock: |
        tls_servername dns.quad9.net
        health_check 5s
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
    - name: hosts
      configBlock: |
        77.111.244.210.sec-tunnel.com
        77.111.244.37.sec-tunnel.com
        77.111.244.209.sec-tunnel.com
        77.111.245.10.sec-tunnel.com
        77.111.245.12.sec-tunnel.com
        77.111.245.11.sec-tunnel.com
        77.111.245.13.sec-tunnel.com
        77.111.245.14.sec-tunnel.com
        77.111.246.5.sec-tunnel.com
        77.111.246.7.sec-tunnel.com
        77.111.246.14.sec-tunnel.com
        77.111.246.31.sec-tunnel.com
        77.111.246.4.sec-tunnel.com
        77.111.246.8.sec-tunnel.com
        77.111.246.6.sec-tunnel.com
        77.111.246.15.sec-tunnel.com
        77.111.246.126.sec-tunnel.com
        77.111.246.22.sec-tunnel.com
        77.111.246.21.sec-tunnel.com
        77.111.246.38.sec-tunnel.com
        77.111.246.39.sec-tunnel.com
        77.111.246.37.sec-tunnel.com
        77.111.246.23.sec-tunnel.com
        77.111.246.40.sec-tunnel.com
        77.111.247.69.sec-tunnel.com
        77.111.247.74.sec-tunnel.com
        77.111.247.44.sec-tunnel.com
        77.111.247.59.sec-tunnel.com
        77.111.247.68.sec-tunnel.com
        77.111.247.41.sec-tunnel.com
        77.111.247.81.sec-tunnel.com
        77.111.247.21.sec-tunnel.com
        77.111.247.66.sec-tunnel.com
        77.111.247.205.sec-tunnel.com
        77.111.247.137.sec-tunnel.com
        77.111.247.55.sec-tunnel.com
        77.111.247.40.sec-tunnel.com
        77.111.247.119.sec-tunnel.com
        77.111.247.129.sec-tunnel.com
        77.111.247.30.sec-tunnel.com
        77.111.247.49.sec-tunnel.com
        77.111.247.100.sec-tunnel.com
        77.111.247.8.sec-tunnel.com
        77.111.247.46.sec-tunnel.com
        77.111.247.64.sec-tunnel.com
        77.111.247.108.sec-tunnel.com
        77.111.247.191.sec-tunnel.com
        77.111.247.206.sec-tunnel.com
        77.111.247.109.sec-tunnel.com
        77.111.247.31.sec-tunnel.com
        77.111.247.75.sec-tunnel.com
        77.111.247.11.sec-tunnel.com
        77.111.247.99.sec-tunnel.com
        77.111.247.12.sec-tunnel.com
        77.111.247.39.sec-tunnel.com
        77.111.247.73.sec-tunnel.com
        77.111.247.196.sec-tunnel.com
        77.111.247.82.sec-tunnel.com
        77.111.247.57.sec-tunnel.com
        77.111.247.56.sec-tunnel.com
        77.111.247.91.sec-tunnel.com
        77.111.247.251.sec-tunnel.com
        77.111.247.43.sec-tunnel.com
        77.111.247.48.sec-tunnel.com
        77.111.247.190.sec-tunnel.com
        77.111.247.47.sec-tunnel.com
        77.111.247.184.sec-tunnel.com
        77.111.247.185.sec-tunnel.com
        77.111.247.13.sec-tunnel.com
        77.111.247.71.sec-tunnel.com
        77.111.247.189.sec-tunnel.com
        77.111.247.90.sec-tunnel.com
        77.111.247.72.sec-tunnel.com
        77.111.247.5.sec-tunnel.com
        77.111.247.214.sec-tunnel.com
        77.111.247.197.sec-tunnel.com
        77.111.247.159.sec-tunnel.com
        77.111.247.188.sec-tunnel.com
        77.111.247.9.sec-tunnel.com
        77.111.247.147.sec-tunnel.com
        77.111.247.10.sec-tunnel.com
        77.111.247.223.sec-tunnel.com
        77.111.247.7.sec-tunnel.com
        77.111.247.4.sec-tunnel.com
        77.111.247.183.sec-tunnel.com
        77.111.247.169.sec-tunnel.com
        77.111.247.128.sec-tunnel.com
        77.111.247.224.sec-tunnel.com
        77.111.247.22.sec-tunnel.com
        77.111.247.215.sec-tunnel.com
        77.111.247.186.sec-tunnel.com
        77.111.247.6.sec-tunnel.com
        77.111.247.146.sec-tunnel.com
        77.111.247.187.sec-tunnel.com
        77.111.247.67.sec-tunnel.com
        77.111.247.120.sec-tunnel.com
        77.111.247.60.sec-tunnel.com
        77.111.247.241.sec-tunnel.com
        77.111.247.233.sec-tunnel.com
        77.111.247.54.sec-tunnel.com
        77.111.247.117.sec-tunnel.com
        77.111.247.232.sec-tunnel.com
        77.111.247.252.sec-tunnel.com
        77.111.247.242.sec-tunnel.com
        77.111.247.160.sec-tunnel.com
        77.111.247.45.sec-tunnel.com
        77.111.247.61.sec-tunnel.com
        77.111.247.58.sec-tunnel.com
        77.111.247.182.sec-tunnel.com
        77.111.247.77.sec-tunnel.com
        77.111.247.180.sec-tunnel.com
        77.111.247.181.sec-tunnel.com
        77.111.247.168.sec-tunnel.com
        77.111.247.65.sec-tunnel.com
        77.111.247.138.sec-tunnel.com
        77.111.247.250.sec-tunnel.com
        77.111.247.253.sec-tunnel.com
        77.111.247.50.sec-tunnel.com
        77.111.247.76.sec-tunnel.com
        77.111.247.62.sec-tunnel.com
        fallthrough