apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "searx.fullname" . }}
  labels:
    app: {{ template "searx.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  settings.yml: |
{{ toYaml .Values.searxSettings | indent 4 }}
  wireproxy.conf: |
{{ .Values.wireproxy | indent 4 }}