apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "searx.fullname" . }}
  labels:
    app: {{ template "searx.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    autoupdate/scheduled: "true"
  annotations:
    autoupdate/config: >
      searx: latest$
spec:
  replicas: {{ .Values.searx.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "searx.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ template "searx.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.searx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      imagePullSecrets:
        - name: imagepullsecrets-docker-registry
      volumes:
      - name: config-searx
        configMap:
          name: {{ template "searx.fullname" . }}
      containers:
      - name: "{{ .Chart.Name }}-wireproxy"
        image: "ghcr.io/pufferffish/wireproxy:latest"
        imagePullPolicy: {{ .Values.searx.image.pullPolicy }}
        args:
        - "-s"
        - "-c"
        - "/wireproxy.conf"
        volumeMounts:
        - name: config-searx
          mountPath: /wireproxy.conf
          subPath: wireproxy.conf
      - name: "{{ .Chart.Name }}-tor"
        image: "osminogin/tor-simple"
        imagePullPolicy: {{ .Values.searx.image.pullPolicy }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.searx.image.repository }}:{{ .Values.searx.image.tag }}"
        imagePullPolicy: {{ .Values.searx.image.pullPolicy }}
        env:
        - name: PGID
          value: "991"
        - name: PUID
          value: "991"
        - name: BIND_ADDRESS
          value: "0.0.0.0"
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-searx
          mountPath: /etc/searxng/settings.yml
          subPath: settings.yml
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
        resources:
{{ toYaml .Values.searx.resources | indent 10 }}
        readinessProbe:
          periodSeconds: 10
          failureThreshold: 20
          httpGet:
            port: 8888
            path: /
        livenessProbe:
          periodSeconds: 10
          failureThreshold: 20
          httpGet:
            port: 8888
            path: /
      restartPolicy: Always
