apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "searx.fullname" . }}-morty
  labels:
    app: {{ template "searx.name" . }}-morty
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.morty.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "searx.name" . }}-morty
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "searx.name" . }}-morty
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.morty.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.morty.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: morty
        image: "{{ .Values.morty.image.repository }}:{{ .Values.morty.image.tag }}"
        imagePullPolicy: {{ .Values.morty.image.pullPolicy }}
        args: ["-timeout", "6"]
        env:
        - name: MORTY_KEY
          value: "{{ .Values.morty.key }}"
        - name: MORTY_ADDRESS
          value: "0.0.0.0:3000"
        ports:
        - containerPort: 3000
        securityContext:
          capabilities:
            drop:
            - ALL
        resources:
{{ toYaml .Values.morty.resources | indent 10 }}
        readinessProbe:
          httpGet:
            port: 3000
            path: /
        livenessProbe:
          httpGet:
            port: 3000
            path: /
      restartPolicy: Always
