{{- if .Values.filtron.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "searx.fullname" . }}-filtron
  labels:
    app: {{ template "searx.name" . }}-filtron
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "searx.fullname" . }}-filtron
  minReplicas: {{ .Values.filtron.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.filtron.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.filtron.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
