{{- if .Values.ingress.enabled -}}
{{- $fullName := include "searx.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "searx.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations.main }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              {{ if $.Values.filtron.enabled }}
              serviceName: "{{ $fullName }}-filtron"
              {{ else }}
              serviceName: "{{ $fullName }}"
              {{ end }}
              servicePort: http
          - path: /morty
            backend:
              serviceName: "{{ $fullName }}-morty"
              servicePort: http
  {{- end }}
{{- if eq .Values.filtron.enabled false }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-search
  labels:
    app: {{ template "searx.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations.search }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /search
            backend:
              serviceName: "{{ $fullName }}"
              servicePort: http
  {{- end }}
{{- end }}
{{- end }}