{{- if .Values.ingress.enabled -}}
{{- $fullName := include "searx.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "searx.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations.main }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                {{ if $.Values.filtron.enabled }}
                name: "{{ $fullName }}-filtron"
                {{ else }}
                name: "{{ $fullName }}"
                {{ end }}
                port:
                  name: http
          - path: /morty
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ $fullName }}-morty"
                port:
                  name: http
  {{- end }}
{{- if eq .Values.filtron.enabled false }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-search
  labels:
    app: {{ template "searx.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations.search }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /search
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ $fullName }}"
                port:
                  name: http
  {{- end }}
{{- end }}
{{- end }}