apiVersion: v1
kind: Service
metadata:
  name: {{ template "searx.fullname" . }}
  labels:
    app: {{ template "searx.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: {{ template "searx.name" . }}
    release: {{ .Release.Name }}
