{{- if .Values.filtron.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "searx.fullname" . }}-filtron
  labels:
    app: {{ template "searx.name" . }}-filtron
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 4004
    targetPort: 4004
  selector:
    app: {{ template "searx.name" . }}-filtron
    release: {{ .Release.Name }}
{{- end }}