config:
  ## Resources you want to watch
  resources:
    - name: pod                # Name of the resources e.g pod, deployment, ingress, etc.
      namespaces:               # List of namespaces, "all" will watch all the namespaces
        include:  
          - all
        ignore:
          - kube-system
      events:                   # List of lifecycle events you want to receive, e.g create, update, delete, error OR all
        - create
        - update
        - delete
        - error
    - name: job
      namespaces:
        include:  
          - all
        ignore:
          - kube-system
      events:
        - all
    - name: service
      namespaces:
        include:  
          - all
        ignore:
          - kube-system
      events:
        - create
        - delete
        - error
    - name: deployment
      namespaces:
        include:  
          - all
      events:
        - create
        - update
        - delete
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.availableReplicas
    - name: statefulset
      namespaces:
        include:  
          - all
      events:
        - create
        - update
        - delete
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.readyReplicas
    - name: daemonset
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - update
        - delete
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.numberReady
    - name: job
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - update
        - delete
        - error
      updateSetting:
        includeDiff: true
        fields:
          - spec.template.spec.containers[*].image
          - status.conditions[*].type
    - name: node
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - delete
        - error
