#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: quay.io/unixfox/eternaljukebox
  # -- image tag
  tag: 7c76ed4
  # -- image pull policy
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/arch: amd64

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

mariadb:
  auth:
    database: eternaljukebox
    username: eternal_user
  primary:
    nodeSelector:
      kubernetes.io/arch: amd64

env:
  DOMAIN: "localhost"
  PORT: "8080"
  SQL_TYPE: "mysql"
  SQL_PORT: "3306"
  SQL_DATABASE_NAME: "eternaljukebox"
  SQL_USERNAME: "eternal_user"
  SQL_HOST: "eternaljukebox-mariadb"

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false