apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "pgbouncer.name" . }}
    helm.sh/chart: {{ include "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  pgbouncer.ini: |
    [databases]
{{- range $key, $val := .Values.config.databases }}
    {{ $key }} ={{ range $k, $v := $val }} {{ $k }}={{ $v }}{{ end }}
{{- end }}

    [pgbouncer]
    listen_addr = *
    listen_port = 5432
    auth_file = /etc/userlist/userlist.txt
    admin_users = {{ .Values.config.adminUser }}
{{- if .Values.config.authUser }}
    auth_user = {{ .Values.config.authUser }}
{{- end }}
{{- range $key, $val := .Values.config.pgbouncer }}
    {{ $key }} = {{ $val }}
{{- end }}
