apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgbouncer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    helm.sh/chart: {{ template "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
