{{- if not .Values.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pgbouncer.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    helm.sh/chart: {{ template "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ if .Values.serviceAccount.annotations -}}
  annotations: {{ .Values.serviceAccount.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
{{- end }}
