name: invidious

image:
  repository: quay.io/invidious/invidious
  tag: latest
  pullPolicy: Always

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 50

refresh:
  enabled: true

hostNetwork: false
containerPorts: true

ingress:
  enabled: true
  main:
    annotations:
      kubernetes.io/tls-acme: "true"
  others:
    - path: /videoplayback
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header Access-Control-Allow-Origin *;
          add_header Access-Control-Allow-Headers *;
      backend:
        serviceName: ""
  hosts:
  - example.org
  tls:
   - secretName: chart-invidious-tls
     hosts:
     - example.org

ytproxy:
  hostNetwork: true
  image:
    repository: 1337kavin/ytproxy
    tag: latest
    pullPolicy: Always
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

resources: {}
  #requests:
  #  cpu: 100m
  #  memory: 64Mi
  #limits:
  #  cpu: 800m
  #  memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# See https://github.com/helm/charts/tree/master/stable/postgresql
postgresql:
  enabled: false
  auth:
    username: kemal
    password: kemal
    database: invidious
    postgresPassword: kemal
  primary:
    initdb:
      user: kemal
      password: kemal
      scriptsConfigMap: invidious-postgresql-init
    persistence:
      mountPath: /data/
  postgresqlDataDir: /data/pgdata
  
  image:
    repository: library/postgres
    tag: 10

extraVolumesMounts: []
extraVolumes: []

# Adapted from ../config/config.yml
config:
  channel_threads: 1
  feed_threads: 1
  db:
    user: kemal
    password: kemal
    host: invidious-postgresql
    port: 5432
    dbname: invidious
  full_refresh: false
  https_only: false
  domain:
