{{ if .Values.powerdns.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.fullname" . }}-secret
  labels:
    release: {{ .Release.Name }}-secret
    chart: {{ template "powerdns.chart" . }}
    component: {{ .Release.Name }}-{{ .Values.Component }}-secret
type: Opaque
data:
  {{ if .Values.powerdns.apikey }}
  PDNS_APIKEY: {{ .Values.powerdns.apikey | b64enc }}
  {{ else }}
  PDNS_APIKEY: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
  {{ if .Values.mariadb.mysql_pass }}
  MYSQL_PASS: {{ .Values.mariadb.mysql_pass | b64enc }}
  {{ else }}
  MYSQL_PASS: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
  {{ if .Values.mariadb.mysql_rootpass }}
  MYSQL_ROOTPASS: {{ .Values.mariadb.mysql_rootpass | b64enc }}
  {{ end }}
  {{ if .Values.powerdnsadmin.secret }}
  PDNSADMIN_SECRET: {{ .Values.powerdnsadmin.secret | b64enc }}
  {{ else }}
  PDNSADMIN_SECRET: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
{{ end }}
