apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    release: {{ .Release.Name }}
    chart: '{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}'
type: Opaque
data:
  OCI_TENANCY: {{ .Values.config.tenancy | required "config.tenancy must be set" | b64enc  }}
  OCI_USER: {{ .Values.config.user | required "config.user must be set" | b64enc  }}
  OCI_FINGERPRINT: {{ .Values.config.fingerprint | required "config.fingerprint must be set" | b64enc  }}
  OCI_PRIVATE_KEY: {{ .Values.config.privateKey | required "config.privateKey must be set" | b64enc }}