name: nitter
description: nitter chart
version: 0.0.1
apiVersion: v1
keywords:
  - docker-compose
sources:
home:
dependencies:
- name: redis
  version: ~12.2.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled