apiVersion: v2
appVersion: latest
name: nitter
version: 1.0.0
keywords:
  - nitter
sources:
  - https://hub.docker.com/r/epenguincom/nitter/
  - https://github.com/zedeus/nitter
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.0.1
  - name: redis
    version: ~12.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
