apiVersion: v2
appVersion: latest
name: nitter
version: 1.0.0
keywords:
  - nitter
sources:
  - https://hub.docker.com/r/epenguincom/nitter/
  - https://github.com/zedeus/nitter
dependencies:
  - name: application
    repository: https://stakater.github.io/stakater-charts
    version: 2.1.18
    alias: nitter
  - name: redis
    version: 1.1.3
    repository: https://charts.pascaliske.dev
    condition: redis.enabled
