apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-scaleway-secret"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.scalewaysecret.awsAccessKeyId | required "scalewaysecret.awsAccessKeyId must be set" | b64enc | quote }}
  AWS_ENDPOINTS: {{ .Values.scalewaysecret.awsEndpoint | required "scalewaysecret.awsEndpoint must be set" | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.scalewaysecret.awsSecretAccessKey | required "scalewaysecret.awsSecretAccessKey must be set" | b64enc | quote }}
type: Opaque