keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  approvals: 0
  # images to track and update
  images: 
    - repository: image.repository
      tag: image.tag
    - repository: ytproxy.image.repository
      tag: ytproxy.image.tag

image:
  repository: unixfox/invidious-custom
  tag: new-latest

postgresql:
  persistence:
    size: "200Gi"
  image:
    repository: library/postgres
    tag: 10

replicaCount: 6

ytproxy:
  hostNetwork: true
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101

ingress:
  enabled: true
  hosts:
  - yewtu.be
  - www.yewtu.be
  - webhook.yewtu.be
  - wttprx.yewtu.be
  tls:
   - secretName: chart-invidious-tls
     hosts:
     - yewtu.be
     - www.yewtu.be
     - webhook.yewtu.be
     - wttprx.yewtu.be

extraVolumes:
  - name: redissocket
    hostPath:
      path: /tmp/redis-invidious
      type: DirectoryOrCreate

extraVolumesMounts:
  - name: redissocket
    mountPath: /tmp/redis-invidious

config:
  enable_user_notifications: false
  redis_socket: "/tmp/redis-invidious/redis.sock"
  use_quic: false
  channel_threads: 0
  feed_threads: 0
  jobs:
    clear_expired_items:
      enable: false
    refresh_channels:
      enable: false
    refresh_feeds:
      enable: false
  modified_source_code_url: https://github.com/unixfox/invidious-custom
  output: STDOUT
  log_level: Error
  full_refresh: false
  https_only: true
  domain: yewtu.be
  decrypt_polling: true
  popular_enabled: false
  captcha_enabled: false
  login_enabled: true
  registration_enabled: false
  statistics_enabled: true
  external_port: 443
  default_user_preferences:
    annotations: false
    annotations_subscribed: false
    autoplay: true
    captions:
    - ""
    - ""
    - ""
    comments:
    - youtube
    - ""
    continue: false
    continue_autoplay: true
    dark_mode: ""
    latest_only: false
    listen: false
    local: false
    locale: en-US
    max_results: 40
    notifications_only: false
    player_style: invidious
    quality: hd720
    quality_dash: auto
    default_home: ""
    feed_menu:
    - Trending
    - Subscriptions
    - Playlists
    related_videos: true
    sort: published
    thin_mode: false
    unseen_only: false
    video_loop: false
    extend_desc: false
    volume: 100
    save_player_pos: false
    watch_history: false
    force_resolve: ipv6
  dmca_content: []
  check_tables: true
  cache_annotations: false
  hsts: true
  disable_proxy:
  - downloads
  - livestreams
  port: 3000
  pool_size: 100
