persistence:
  enabled: true
  size: 80Gi
  storageClass: "local-path"

storageClass:
  defaultClass: true
  mountOptions:
    - async
    - vers=3
    - nfsvers=4.2
    - noatime

nodeSelector:
  kubernetes.io/hostname: oraclefree3