brudi:
  resources: {}
  args: ["-c", "/home/brudi/.brudi.yml", "mysqldump", "--restic", "--cleanup"]
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
  envs:
    - name: "RESTIC_REPOSITORY"
      value: "rclone:foo:bar"
  image:
    repository: quay.io/unixfox/brudi
    tag: "latest"
    pullPolicy: IfNotPresent
    runAsUser: 1000
    allowPrivilegeEscalation: false
  config:
    mysqldump:
      options:
        flags:
          host: 9.9.9.9
          port: 3306
          password: password
          user: backup
          gzip: true
          databases: ["mydb"]
          resultFile: /tmp/mysql.sqldump
    restic:
      global:
        flags:
          CacheDir: "/tmp/cache"
      forget:
        flags:
          keepLast: 30
          keepHourly: 24
          keepDaily: 7
          keepWeekly: 2
          keepMonthly: 6
          keepYearly: 2

restic:
  password: "yourpassword"
  repository: "rclone:foo:bar"

rclone:
  config: |
    [remote]
    type = s3
    provider = Scaleway

cronjob:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  schedule: "0 * * * *"

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
affinity: {}
tolerations: []