brudi:
  resources: {}
  command:
  - /bin/ash
  - -cx
  - "until nc -z 127.0.0.1 8080; do echo waiting for rclone; sleep 2; done;
    brudi -c /etc/brudi.yml mysqldump --restic --cleanup;
    echo -ne 'PUT /supervisor/shutdown HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n' | nc 127.0.0.1 9001"
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
  envs:
    - name: "RESTIC_REPOSITORY"
      value: "rest:http://localhost:8080/"
  image:
    repository: quay.io/mittwald/brudi
    tag: "latest"
    pullPolicy: IfNotPresent
    runAsUser: 10001
    allowPrivilegeEscalation: false
  config:
    mysqldump:
      options:
        flags:
          host: 9.9.9.9
          port: 3306
          password: password
          user: backup
          gzip: true
          databases: ["mydb"]
          resultFile: /tmp/mysql.sqldump
    restic:
      global:
        flags:
          CacheDir: "/tmp/cache"
      forget:
        flags:
          keepLast: 48
          keepHourly: 24
          keepDaily: 7
          keepWeekly: 2
          keepMonthly: 6
          keepYearly: 2

restic:
  password: "yourpassword"

rclone:
  resources: {}
  # limits:
  #   cpu: 10m
  #   memory: 20Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
  image:
    repository: unixfox/rclone-with-supervisord
    tag: "latest"
    pullPolicy: IfNotPresent
    runAsUser: 10001
    allowPrivilegeEscalation: false
  config: |
    [remote]
    type = s3
    provider = Scaleway

supervisord:
  config: |
    [inet_http_server]
    port=localhost:9001
    [program:rclone]
    command = /usr/local/bin/rclone serve --retries 999 -vvvvv restic union:/
    stdout_logfile=/dev/stdout
    redirect_stderr=true
    autostart=true
    autorestart=true
    startretries=999

cronjob:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  schedule: "0 * * * *"

nodeSelector:
  kubernetes.io/os: linux
affinity: {}
tolerations: []