postgresql:
  enabled: true
  primary:
    nodeSelector:
      kubernetes.io/hostname: frhb71656ds

nodeSelector:
  kubernetes.io/hostname: frhb71656ds

ingress:
  enabled: true
  hosts:
  - eu2.proxy.yewtu.be
  tls:
   - secretName: chart-invidious-eu2-tls
     hosts:
     - eu2.proxy.yewtu.be
  

config:
  domain: eu2.proxy.yewtu.be
  db:
    host: invidious-proxy-eu-2-postgresql-headless