image:
  registry: "quay.io"
  repository: unixfox/pgbouncer
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

config:
  databases:
    invidious:
      host: stolon-proxy
      port: 5432
  pgbouncer:
    server_tls_sslmode: prefer
    max_client_conn: 500
    ignore_startup_parameters: extra_float_digits
    pool_mode: transaction