apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller daemonSet --chart
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: "2015"
    port: 2015
    targetPort: 2015
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}