apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-rclone.fullname" . }}-configmap
  labels:
{{ include "kube-rclone.labels" . | indent 4 }}
data:
  rclone.conf: |
{{ required "rclone.config must be set" .Values.rclone.config | indent 4 }}