{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
# apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "keel.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # name: {{ template "keel.name" . }}
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
