apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-invidious-ro
spec:
  cluster:
    name: invidious-pg
  instances: 2
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1500"
      default_pool_size: "25"