image:
  registry: "quay.io"
  repository: unixfox/pgbouncer
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

config:
  databases:
    invidious:
      host: invidious-postgresql
      port: 5432
  pgbouncer:
    server_tls_sslmode: prefer
    max_client_conn: 1500
    ignore_startup_parameters: extra_float_digits
    pool_mode: transaction
    default_pool_size: 30