apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
data:
  Corefile: |
    {{ .Values.config.clusterDomain }}:53 {
      errors
      cache {
        success 9984 30
        denial 9984 5
      }
      reload
      loop
      {{- if .Values.config.upstreamDnsUseTcp }}
      forward . {{ .Values.config.nodeLocalSvcIp }} {
        force_tcp
      }
      {{ else }}
      forward . {{ .Values.config.nodeLocalSvcIp }}
      {{- end }}
      prometheus :9253
      health :8080
    }
    in-addr.arpa:53 {
      errors
      cache 30
      reload
      loop
      {{- if .Values.config.upstreamDnsUseTcp }}
      forward . {{ .Values.config.nodeLocalSvcIp }} {
        force_tcp
      }
      {{ else }}
      forward . {{ .Values.config.nodeLocalSvcIp }}
      {{- end }}
      prometheus :9253
    }
    ip6.arpa:53 {
      errors
      cache 30
      reload
      loop
      {{- if .Values.config.upstreamDnsUseTcp }}
      forward . {{ .Values.config.nodeLocalSvcIp }} {
        force_tcp
      }
      {{ else }}
      forward . {{ .Values.config.nodeLocalSvcIp }}
      {{- end }}
      prometheus :9253
    }
    .:53 {
      errors
      cache 30
      reload
      loop
      {{- if .Values.config.upstreamDnsUseTcp }}
      forward . {{ .Values.config.upstreamDns }} {
        force_tcp
      }
      {{ else }}
      forward . {{ .Values.config.upstreamDns }}
      {{- end }}
      prometheus :9253
    }
