apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}-upstream
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: dns-udp
      port: {{ .Values.service.udpPort }}
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.service.tcpPort }}
      targetPort: 53
      protocol: TCP
  selector:
    {{- toYaml .Values.service.upstreamSelector | nindent 4 }}
